# Azure Pipelines for GitHub :)
# More info: https://docs.microsoft.com/en-us/azure/devops/pipelines/?view=vsts
trigger:
  branches:
    include:
      - master
      - azure-pipelines
      - function-prod-health
      - Client-SDK
      - mobile-android
  paths:
    include:
      - 'Src/FaceExplorer-App'
      - 'Src/Backend'
      - 'Src/Mobile'
      - 'azure-pipelines.yml'
      - 'azure-pipelines-angular.yml'
      - 'azure-pipelines-function.yml'
      - 'azure-pipelines-webapp.yml'
      - 'azure-pipelines-nuget.yml'

variables:
  buildConfiguration: 'Release'

jobs:
- template: azure-pipelines-webapp.yml
  parameters:
    Name: ContosoBackendAPIs
    RestoreBuildProjects: '**/*.API.csproj'
    BuildConfiguration: 'Debug'
    WorkingDirectory: 'Src/Backend/Contoso.CognitivePipeline.API'
    ArtifactName: 'ContosoBackendAPIs'
    PublishWebApp: True

- template: azure-pipelines-webapp.yml
  parameters:
    Name: ContosoBackendFunction
    RestoreBuildProjects: '**/*.BackgroundServices.csproj'
    BuildConfiguration: 'Release'
    WorkingDirectory: 'Src/Backend/Contoso.CognitivePipeline.BackgroundServices'
    ArtifactName: 'ContosoBackendFunctions'
    PublishWebApp: False
    ZipAfterPublish: False

- template: azure-pipelines-angular.yml
  parameters:
    Name: FaceExplorerApp

- template: azure-pipelines-nuget.yml
  parameters:
    Name: 'ClientSDK'
    WorkingDirectory: 'Src/Backend/CognitivePipeline.ClientSDK'

- template: azure-pipelines-tests.yml
  parameters:
    Name: 'Tests'
